import { useEffect, useMemo, useState } from 'react';

const locale = {
  es: {
    nav: ['Inicio', 'Nosotros', 'Servicios', 'Proceso', 'Contacto'], book: 'Agendar una reunión',
    heroTag: 'SOFTWARE · SYSTEMS · SOLUTIONS', heroTitle: 'Ingeniería que convierte operaciones manuales en sistemas automáticos', heroText: 'Diseñamos, desarrollamos e implementamos software a medida, sistemas ERP y automatización de procesos para empresas medianas y grandes que necesitan operar sin fricción.', servicesLink: 'Ver servicios',
    aboutTag: 'QUIÉNES SOMOS', aboutTitle: 'Un equipo de ingeniería, no un vendedor de software', about: ['NUVYRA nació dentro de la operación: plantas, depósitos, administración y equipos de servicio donde la información vivía en planillas y las decisiones llegaban tarde.', 'Cada proyecto empieza con un diagnóstico en terreno: relevamos el flujo, medimos dónde se pierde tiempo y definimos qué conviene automatizar primero.', 'Trabajamos como una extensión de tu equipo de TI y operaciones: código documentado, usuarios capacitados y una hoja de ruta clara después de la puesta en marcha.'],
    serviceTag: 'QUÉ HACEMOS', serviceTitle: 'Seis servicios que cubren toda la vida de un sistema', serviceLead: 'Desde el primer diagnóstico hasta la operación diaria de la plataforma. Podés empezar por uno y crecer desde ahí.', processTag: 'CÓMO TRABAJAMOS', processTitle: 'Un proceso de cinco pasos, sin cajas negras', consultTag: 'CONSULTORÍA', consultTitle: 'Contanos qué proceso te está costando más tiempo', consultText: 'Con una llamada de 45 minutos alcanza para decirte si conviene automatizarlo, qué implicaría y cuánto costaría aproximadamente.', consultButton: 'Solicitar una consultoría gratuita',
    contactTag: 'CONTÁCTANOS', contactTitle: 'Hablemos de tu operación', contactLead: 'Escribinos con una descripción breve del proceso y respondemos dentro de un día hábil.', email: 'CORREO', location: 'UBICACIÓN', hours: 'HORARIO DE ATENCIÓN', hoursText: 'Lunes a viernes · 9:00–18:00', name: 'Nombre *', company: 'Empresa', emailLabel: 'Correo *', phone: 'Teléfono', interest: 'Servicio de interés *', message: 'Mensaje *', consent: 'Acepto que NUVYRA guarde estos datos para contactarme por mi consulta.', send: 'Enviar consulta', sending: 'Enviando…', select: 'Seleccioná un servicio', success: 'Gracias por escribir. Recibimos tu consulta y te respondemos dentro de un día hábil.', footer: 'Ingeniería de software, implementación de ERP y automatización de procesos para empresas que necesitan operar sin fricción.', rights: '© 2026 NUVYRA. Todos los derechos reservados.', privacy: 'Política de privacidad · Términos',
    services: [['Desarrollo de software a medida', 'Aplicaciones web y móviles construidas para el proceso real del negocio.', ['Análisis funcional y técnico', 'Web, móvil y portales internos', 'Pruebas automatizadas y documentación']], ['Implementación de ERP', 'Análisis, parametrización, migración de datos y puesta en marcha.', ['Relevamiento de procesos', 'Parametrización y módulos propios', 'Migración de datos y capacitación']], ['Automatización de procesos', 'Reglas, aprobaciones y robots que eliminan tareas repetitivas.', ['Auditoría de tareas y tiempos', 'Bots para carga repetitiva', 'Flujos de aprobación y alertas']], ['Integración de sistemas y APIs', 'Conectamos ERP, CRM, e-commerce y sistemas legados.', ['APIs REST y middleware', 'Conectores legacy', 'Trazabilidad y monitoreo']], ['Business Intelligence y analítica', 'Tableros sobre una única fuente de verdad.', ['Data warehouse y ETL', 'KPIs operativos', 'Reportes automáticos']], ['Soporte, mantenimiento y cloud', 'Infraestructura y mejora continua para crecer sin fricción.', ['SLA acordado', 'Migración a cloud y backups', 'Monitoreo 24/7']]],
    steps: [['Diagnóstico', 'Relevamos el proceso, medimos tiempos y acordamos prioridades.'], ['Diseño de la solución', 'Arquitectura, alcance, plazos y presupuesto documentados.'], ['Desarrollo', 'Ciclos de dos semanas con demos para ajustar el avance.'], ['Implementación y capacitación', 'Go-live controlado, migración y capacitación práctica.'], ['Soporte y evolución', 'SLA, monitoreo y una hoja de ruta de mejoras.']],
  },
  en: {
    nav: ['Home', 'About us', 'Services', 'Process', 'Contact'], book: 'Book a meeting',
    heroTag: 'SOFTWARE · SYSTEMS · SOLUTIONS', heroTitle: 'Engineering that turns manual operations into automated systems', heroText: 'We design, develop and implement custom software, ERP systems and process automation for mid-sized and large companies that need to operate without friction.', servicesLink: 'View services',
    aboutTag: 'WHO WE ARE', aboutTitle: 'An engineering team, not a software salesperson', about: ['NUVYRA was born inside operations: plants, warehouses, administration and service teams where information lived in spreadsheets and decisions came late.', 'Every project begins with an on-site diagnosis: we map the flow, measure where time is lost and define what to automate first.', 'We work as an extension of your IT and operations team: documented code, trained users and a clear roadmap after go-live.'],
    serviceTag: 'WHAT WE DO', serviceTitle: 'Six services covering the entire life of a system', serviceLead: 'From the first diagnosis to the platform’s daily operation. Start with one and grow from there.', processTag: 'HOW WE WORK', processTitle: 'A five-step process, with no black boxes', consultTag: 'CONSULTING', consultTitle: 'Tell us which process is costing you the most time', consultText: 'A 45-minute call is enough to tell you whether it is worth automating, what it involves and its approximate cost.', consultButton: 'Request a free consultation',
    contactTag: 'CONTACT US', contactTitle: 'Let’s talk about your operation', contactLead: 'Write us a brief description of the process and we will respond within one business day.', email: 'EMAIL', location: 'LOCATION', hours: 'BUSINESS HOURS', hoursText: 'Monday to Friday · 9:00–18:00', name: 'Name *', company: 'Company', emailLabel: 'Email *', phone: 'Phone', interest: 'Service of interest *', message: 'Message *', consent: 'I agree that NUVYRA may store this information to contact me about my enquiry.', send: 'Send enquiry', sending: 'Sending…', select: 'Select a service', success: 'Thanks for writing. We received your enquiry and will reply within one business day.', footer: 'Software engineering, ERP implementation and process automation for companies that need to operate without friction.', rights: '© 2026 NUVYRA. All rights reserved.', privacy: 'Privacy policy · Terms',
    services: [['Custom software development', 'Web and mobile applications built for the real business process.', ['Functional and technical analysis', 'Web, mobile and internal portals', 'Automated testing and documentation']], ['ERP implementation', 'Analysis, configuration, data migration and go-live.', ['Process mapping', 'Configuration and custom modules', 'Data migration and training']], ['Process automation', 'Rules, approvals and bots that eliminate repetitive work.', ['Task and time audit', 'Repetitive data-entry bots', 'Approval flows and alerts']], ['Systems and API integration', 'We connect ERP, CRM, e-commerce and legacy systems.', ['REST APIs and middleware', 'Legacy connectors', 'Traceability and monitoring']], ['Business Intelligence and analytics', 'Dashboards on a single source of truth.', ['Data warehouse and ETL', 'Operational KPIs', 'Automated reports']], ['Support, maintenance and cloud', 'Infrastructure and continuous improvement to grow without friction.', ['Agreed SLA', 'Cloud migration and backups', '24/7 monitoring']]],
    steps: [['Diagnosis', 'We map the process, measure times and agree on priorities.'], ['Solution design', 'Architecture, scope, schedule and budget documented.'], ['Development', 'Two-week cycles with demos to adjust progress.'], ['Implementation and training', 'Controlled go-live, migration and hands-on training.'], ['Support and evolution', 'SLA, monitoring and an improvement roadmap.']],
  },
};
const links = ['#inicio', '#nosotros', '#servicios', '#proceso', '#contacto'];
const formDefaults = { name: '', company: '', email: '', phone: '', service: '', message: '', consent: false, website: '' };

function Logo({ footer = false }) { return <a className={`logo ${footer ? 'logo-footer' : ''}`} href="#inicio" aria-label="NUVYRA"><img src="/images/nuvyra-logo-transparent.png" alt="Logotipo NUVYRA" /><span><b>NUVYRA</b><small>SOFTWARE · SYSTEMS · SOLUTIONS</small></span></a>; }
function Field({ label, error, children }) { return <label className="field"><span>{label}</span>{children}{error && <em className="error">{error}</em>}</label>; }

function ContactForm({ t }) {
  const [form, setForm] = useState(formDefaults); const [errors, setErrors] = useState({}); const [notice, setNotice] = useState(null); const [sending, setSending] = useState(false);
  const update = ({ target }) => setForm((old) => ({ ...old, [target.name]: target.type === 'checkbox' ? target.checked : target.value }));
  const submit = async (event) => { event.preventDefault(); const next = { name: form.name.trim().length < 2 ? 'Please enter a valid name.' : '', email: !/^\S+@\S+\.\S+$/.test(form.email) ? 'Please enter a valid email.' : '', service: !form.service ? 'Please choose a service.' : '', message: form.message.trim().length < 10 ? 'Please enter at least 10 characters.' : '', consent: !form.consent ? 'Please accept to continue.' : '' }; setErrors(next); if (Object.values(next).some(Boolean)) return; setSending(true); setNotice(null); try { const response = await fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to send your enquiry.'); setForm(formDefaults); setNotice({ ok: true, text: t.success }); } catch (error) { setNotice({ ok: false, text: error.message }); } finally { setSending(false); } };
  const input = (name) => ({ name, value: form[name], onChange: update, 'aria-invalid': Boolean(errors[name]), maxLength: name === 'message' ? 1000 : undefined });
  return <form className="contact-form" onSubmit={submit} noValidate><div className="form-grid"><Field label={t.name} error={errors.name}><input {...input('name')} placeholder={t.name.replace(' *', '')} /></Field><Field label={t.company}><input {...input('company')} placeholder={t.company} /></Field><Field label={t.emailLabel} error={errors.email}><input {...input('email')} type="email" placeholder="you@company.com" /></Field><Field label={t.phone}><input {...input('phone')} type="tel" placeholder="+00 000 000 0000" /></Field></div><Field label={t.interest} error={errors.service}><select {...input('service')}><option value="">{t.select}</option>{t.services.map(([title]) => <option value={title} key={title}>{title}</option>)}</select></Field><Field label={t.message} error={errors.message}><textarea {...input('message')} rows="5" placeholder={t.message.replace(' *', '')} /></Field><input className="honeypot" tabIndex="-1" autoComplete="off" {...input('website')} aria-hidden="true" /><label className="consent"><input {...input('consent')} type="checkbox" /><span>{t.consent}</span></label>{errors.consent && <p className="error">{errors.consent}</p>}<button className="button full" disabled={sending}>{sending ? t.sending : t.send}</button>{notice && <p className={`notice ${notice.ok ? 'success' : 'error'}`} role="status">{notice.text}</p>}</form>;
}

export default function App() {
  const [lang, setLang] = useState('es'); const [menuOpen, setMenuOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const t = useMemo(() => locale[lang], [lang]);
  useEffect(() => { document.documentElement.lang = lang; const onScroll = () => setScrolled(window.scrollY > 28); onScroll(); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll); }, [lang]);
  return <><header className={`header ${scrolled ? 'scrolled' : ''}`}><div className="header-inner"><Logo /><div className="navigation-wrap"><div className="language" aria-label="Language"><button className={lang === 'es' ? 'active' : ''} onClick={() => setLang('es')}>ES</button><button className={lang === 'en' ? 'active' : ''} onClick={() => setLang('en')}>EN</button></div><nav className="desktop-nav">{links.map((href, index) => <a href={href} key={href}>{t.nav[index]}</a>)}</nav></div><div className="header-actions"><a className="button small cta" href="#contacto">{t.book}</a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open menu">☰</button></div></div>{menuOpen && <nav className="mobile-nav">{links.map((href, index) => <a href={href} key={href} onClick={() => setMenuOpen(false)}>{t.nav[index]}</a>)}</nav>}</header><main>
    <section id="inicio" className="hero"><div className="hero-content"><p className="eyebrow on-dark">{t.heroTag}</p><h1>{t.heroTitle}</h1><p className="lead">{t.heroText}</p><div className="button-row"><a className="button" href="#contacto">{t.book}</a><a className="text-link" href="#servicios">{t.servicesLink} <span>→</span></a></div></div><div className="hero-orbit" aria-hidden="true"><span /><span /><i>+</i></div></section>
    <section id="nosotros" className="section about"><div className="section-heading"><p className="eyebrow">{t.aboutTag}</p><h2>{t.aboutTitle}</h2></div><div className="about-copy">{t.about.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><div className="value-grid">{[['✦', lang === 'es' ? 'Ingeniería a medida' : 'Tailored engineering'], ['◌', lang === 'es' ? 'Metodología ágil' : 'Agile methodology'], ['↗', lang === 'es' ? 'Acompañamiento continuo' : 'Continuous support'], ['◇', lang === 'es' ? 'Tecnología escalable' : 'Scalable technology']].map(([icon, title]) => <article className="mini-card" key={title}><span>{icon}</span><h3>{title}</h3></article>)}</div></section>
    <section id="servicios" className="section"><div className="section-heading centered"><p className="eyebrow">{t.serviceTag}</p><h2>{t.serviceTitle}</h2><p>{t.serviceLead}</p></div><div className="service-grid">{t.services.map(([title, text, items], index) => <article className="service-card" key={title}><span className="number">0{index + 1}</span><h3>{title}</h3><p>{text}</p><ul>{items.map((item) => <li key={item}>✓ {item}</li>)}</ul></article>)}</div></section>
    <section id="proceso" className="section process"><div className="section-heading centered"><p className="eyebrow">{t.processTag}</p><h2>{t.processTitle}</h2></div><div className="steps">{t.steps.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="consulting"><div><p className="eyebrow">{t.consultTag}</p><h2>{t.consultTitle}</h2><p>{t.consultText}</p></div><a className="button" href="#contacto">{t.consultButton}</a></section>
    <section id="contacto" className="section contact"><div className="contact-grid"><div><p className="eyebrow">{t.contactTag}</p><h2>{t.contactTitle}</h2><p className="lead muted">{t.contactLead}</p><ul className="contact-list"><li><b>{t.email}</b><a href="mailto:nuvyra.solutions@gmail.com">nuvyra.solutions@gmail.com</a></li><li><b>{t.location}</b><span>Lima, Perú</span></li><li><b>{t.hours}</b><span>{t.hoursText}</span></li></ul></div><ContactForm t={t} /></div></section>
  </main><footer><div className="footer-grid"><div><Logo footer /><p>{t.footer}</p></div><div><p className="eyebrow on-dark">{t.serviceTag}</p>{t.services.map(([title]) => <a key={title} href="#servicios">{title}</a>)}</div><div><p className="eyebrow on-dark">{t.contactTag}</p><a href="mailto:nuvyra.solutions@gmail.com">nuvyra.solutions@gmail.com</a><span>Lima, Perú</span></div></div><div className="copyright"><span>{t.rights}</span><span>{t.privacy}</span></div></footer></>;
}
